# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# Machine attaquante : Kali Linux
# Cette machine peut etre remplacé par une debian avec les paquets pour l'attaque 
  config.vm.define "kali" do |machine|
    machine.vm.box = "debian/contrib-stretch64"
    machine.vm.box_url = "debian/contrib-stretch64"
    machine.vm.hostname = "kali"
    machine.vm.network :private_network, ip: "192.168.56.72"
    machine.vm.provider "virtualbox" do |v|
      v.gui = false
      v.customize ["modifyvm", :id, "--name", "kali"]
      v.customize ["modifyvm", :id, "--groups", "/Projet"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end    
    machine.vm.provision "shell", path: "scripts/install_sys.sh"
    machine.vm.provision "shell", path: "scripts/install_attack.sh"  
  end
end
